### ISSUE TITLE
Not working and can't reinstall after recent upgrade

### ISSUE THREAD

**Issue by ibraGut** [SeptemberHX/dde-globalmenu-service#11]
After a recent major upgrade (I postponed it for about 3 weeks), global menu didn't work. I try to reinstall but it says it has broken dependencies, specifically appmenu-qt. I cannot install this either, because it tries to find qt4 libraries and they are not longer there. Same issue with my three PCs.

**Comment by SeptemberHX** [comment]
What is the current system version? I just tested with v20.6 when it released on June 1. At that time, I could install appmenu-qt with apt without problem.

I will test it again with the latest release.

**Comment by ibraGut** [comment]
It is 20.6. I clean reinstall deepin in one of my pc and it worked. Sorry for the issue. Probably I broke something while installing other stuff. I'll check if I can fix it without reinstalling, but now I know the problem is on my side. Thanks!
