### ISSUE TITLE
UOS 编译失败：error: KConfigGroup: 没有那个文件或目录

### ISSUE THREAD

**Issue by video000** [SeptemberHX/dde-globalmenu-service#12]
yag@yag-PC:~/dde-globalmenu-service/build$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for modules 'xcb;xcb'
--   Found xcb, version 1.13.1
--   Found xcb, version 1.13.1
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb.so  
CMake Warning at CMakeLists.txt:27 (find_package):
  By not providing "FindKF5Config.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Config", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Config" with
  any of the following names:

    KF5ConfigConfig.cmake
    kf5config-config.cmake

  Add the installation prefix of "KF5Config" to CMAKE_PREFIX_PATH or set
  "KF5Config_DIR" to a directory containing one of the above files.  If
  "KF5Config" provides a separate development package or SDK, be sure it has
  been installed.

CMake Warning at CMakeLists.txt:28 (find_package):
  By not providing "FindKF5CoreAddons.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5CoreAddons", but CMake did not find one.

  Could not find a package configuration file provided by "KF5CoreAddons"
  with any of the following names:

    KF5CoreAddonsConfig.cmake
    kf5coreaddons-config.cmake

  Add the installation prefix of "KF5CoreAddons" to CMAKE_PREFIX_PATH or set
  "KF5CoreAddons_DIR" to a directory containing one of the above files.  If
  "KF5CoreAddons" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring done
CMake Error at CMakeLists.txt:52 (add_executable):
  Target "dde-globalmenu-service" links to target "KF5::ConfigCore" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:52 (add_executable):
  Target "dde-globalmenu-service" links to target "KF5::ConfigGui" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:52 (add_executable):
  Target "dde-globalmenu-service" links to target "KF5::CoreAddons" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/yag/dde-globalmenu-service/build
yag@yag-PC:~/dde-globalmenu-service/build$ make -j8 package
Scanning dependencies of target dde-globalmenu-service_autogen
Scanning dependencies of target changelog
[  4%] Compressing changelog
[  8%] Generating dbusmenuadaptor.cpp, dbusmenuadaptor.h
[ 13%] Generating menuimporteradaptor.cpp, menuimporteradaptor.h
[ 13%] Built target changelog
[ 17%] Automatic MOC and UIC for target dde-globalmenu-service
[ 17%] Built target dde-globalmenu-service_autogen
[ 21%] Generating menuimporteradaptor.moc
[ 26%] Generating dbusmenuadaptor.moc
Scanning dependencies of target dde-globalmenu-service
[ 30%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/main.cpp.o
[ 34%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/dbusmenutypes_p.cpp.o                                                                          
[ 39%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/menuimporter.cpp.o                                                                             
[ 43%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/dbusmenushortcut_p.cpp.o                                                                       
[ 52%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/gmenu-dbusmenu-proxy/menuproxy.cpp.o                                                           
[ 52%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/gmenu-dbusmenu-proxy/window.cpp.o                                                              
[ 56%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/gmenu-dbusmenu-proxy/menu.cpp.o                                                                
[ 60%] Building CXX object CMakeFiles/dde-globalmenu-service.dir/gmenu-dbusmenu-proxy/utils.cpp.o                                                               
/home/yag/dde-globalmenu-service/gmenu-dbusmenu-proxy/menuproxy.cpp:22:10: fatal error: KConfigGroup: 没有那个文件或目录
 #include <KConfigGroup>
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dde-globalmenu-service.dir/build.make:163：CMakeFiles/dde-globalmenu-service.dir/gmenu-dbusmenu-proxy/menuproxy.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:142：CMakeFiles/dde-globalmenu-service.dir/all] 错误 2
make: *** [Makefile:152：all] 错误 2

**Comment by SeptemberHX** [comment]
需要装上对应的开发依赖包。重点关注错误输出里的：`Could not find a package configuration file provided by xxxx`，然后网上搜索一下对应的依赖包是什么就可以了，比如 `KF5Config` 对应的是 `libkf5config-dev`，然后命令行安装对应的 dev 包即可 `sudo apt install libkf5config-dev`

**Comment by video000** [comment]
谢谢大神，已经成功。就是偶尔有的时候最大化窗口后界面会卡死，不知道为什么。

**Comment by SeptemberHX** [comment]
是不是最大化后，把顶栏当做窗口标题栏拖动了？如果是的话，在设置里把最大化后顶栏拖动功能关掉就行了

**Comment by video000** [comment]
是的，我关闭了那个选项，目前没有再次复现那个bug，谢谢大神了。
