### ISSUE TITLE
Clion globalmenu

### ISSUE THREAD

**Issue by Bluequarks** [SeptemberHX/dde-globalmenu-service#2]
https://www.jetbrains.com/help/clion/menus-and-toolbars.html#linux-native-menu
他这个native menu就是您这个globalmenu吧
Clion官方支持，但我试了试不行。

**Comment by SeptemberHX** [comment]
我这边没问题，在 dde-top-panel 仓库的 readme 里也有 clion 的使用截图，应该是你忘记装了什么包。

**Comment by Bluequarks** [comment]
![image](https://user-images.githubusercontent.com/48249258/93964484-3912d280-fd4f-11ea-9403-9df0c4782388.png)
啊？我应该是按步骤来的啊

**Comment by SeptemberHX** [comment]
。。不知道发生了啥，最新版 2020.2.3 全局菜单失效，之前的版本都没问题。
有待后续研究。

**Comment by Bluequarks** [comment]
> 。。不知道发生了啥，最新版 2020.2.3 全局菜单失效，之前的版本都没问题。
> 有待后续研究。

哦好的，那我换个版本去

**Comment by SeptemberHX** [comment]
已确定是 jetbrains 的问题，具体 issue 见 [youtrack](https://youtrack.jetbrains.com/issue/IDEA-240623?p=DBE-10756)

**Comment by SeptemberHX** [comment]
根据上面的链接，只需要安装插件 JavaFX Runtime 即可，已测试，安装后重启IDE能够正常使用全局菜单
