### ISSUE TITLE
bug 不显示顶栏

### ISSUE THREAD

**Issue by taotao7** [SeptemberHX/dde-globalmenu-service#6]
已经按照文档安装对应依赖和开机自启动，但是没有显示顶栏
![Uploading image.png…]()

**Comment by taotao7** [comment]
![image](https://user-images.githubusercontent.com/24582204/104412468-45919400-55a7-11eb-9a85-e13b26692938.png)

**Comment by SeptemberHX** [comment]
顶栏有另外的程序，这个只是全局菜单的后台进程。

顶栏见 https://github.com/SeptemberHX/dde-top-panel
