### ISSUE TITLE
Deepin 20.6 上这个方案不好使了

### ISSUE THREAD

**Issue by hope250** [SeptemberHX/dde-globalmenu-service#9]
Deepin 20.6 上这个方案不好使了，还有办法吗？

**Comment by SeptemberHX** [comment]
具体是哪个工具啊？这个仓库只是后台暴露菜单的服务，负责菜单显示的有 dde-top-panel 和 chameleon-patch

**Comment by hope250** [comment]
> 具体是哪个工具啊？这个仓库只是后台暴露菜单的服务，负责菜单显示的有 dde-top-panel 和 chameleon-patch

https://bbs.deepin.org/post/224774?id=224774&limit=20&offset=3&postId=1338701
将菜单显示在标题栏上 [2021/08/19]

**Comment by hope250** [comment]
> 具体是哪个工具啊？这个仓库只是后台暴露菜单的服务，负责菜单显示的有 dde-top-panel 和 chameleon-patch

我使用那个帖子 75 楼的建议，搞定了。
先手动安装 `appmenu-qt`
`sudo apt install appmenu-qt`

**Comment by SeptemberHX** [comment]
好的，帖子里以及注明了 appmenu-qt 依赖，后面我会直接把依赖写到 deb 安装包里。

**Comment by SeptemberHX** [comment]
不对啊，安装 deb 包的时候，会自动安装 appmenu-qt 包的啊
